"""empty message

Revision ID: 6922c2779cc3
Revises: 
Create Date: 2020-01-11 19:49:52.823058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6922c2779cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('national_id', sa.String(length=16), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('dob', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
